name: Natasha Japp
favicon: null
layout_spectrum: 0.21381674520671368
typography_spectrum: 0.12336374027654529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07165077654644847
  lightness: 0.11238651699386537
  saturation: 0.5576618502382189
  rhythmicContrast: 0.9278427725657821
purpose: []
